export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const PROFILE_USER = 'PROFILE_USER'
export const PROFILE_USER_SUCCESS = 'PROFILE_USER_SUCCESS'
export const PROFILE_USER_FAILED = 'PROFILE_USER_FAILED'
